apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-nginx
  template:
    metadata:
      labels:
        app: mi-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
